# Generated by Django 4.2.7 on 2024-09-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('nome', models.CharField(max_length=100)),
                ('dt_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
