# Generated by Django 4.2.7 on 2024-09-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_colaborador_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='profissao',
            field=models.CharField(choices=[('teste', 'teste'), ('teste2', 'teste2'), ('teste3', 'teste3')], default='Profissão', max_length=100),
        ),
    ]
