# Generated by Django 4.2.7 on 2024-09-03 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_colaborador_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='alterado_em',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='criado_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='profissao',
            field=models.CharField(choices=[('teste', 'teste'), ('teste2', 'teste2'), ('teste3', 'teste3')], max_length=100),
        ),
    ]
