# Generated by Django 4.2.7 on 2024-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_colaborador_alterado_em_colaborador_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
