# Generated by Django 4.2.7 on 2024-09-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_alter_colaborador_descricao_alter_colaborador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='lider',
        ),
    ]
