# Generated by Django 4.2.7 on 2024-09-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_remove_colaborador_lider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('alterado_em', models.DateField(auto_now=True)),
                ('foto', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
    ]
