# Generated by Django 4.2.7 on 2024-09-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_lider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lider',
        ),
    ]
