# Generated by Django 5.1.3 on 2024-11-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0009_lider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="profissao",
            field=models.CharField(max_length=70),
        ),
    ]
