# Generated by Django 5.1.3 on 2024-11-29 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0010_alter_colaborador_profissao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planejador",
            fields=[
                (
                    "email",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
                ("senha", models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name="colaborador",
            name="alterado_em",
        ),
        migrations.RemoveField(
            model_name="colaborador",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="lider",
            name="alterado_em",
        ),
        migrations.RemoveField(
            model_name="lider",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="lider",
            name="id",
        ),
        migrations.AlterField(
            model_name="lider",
            name="email",
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateField(auto_now_add=True)),
                ("status", models.CharField(max_length=12)),
                ("dh_cadastro", models.DateTimeField(auto_now_add=True)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(blank=True, max_length=300, null=True)),
                ("ocorrencia", models.CharField(blank=True, max_length=300, null=True)),
                ("dh_inicio", models.DateTimeField()),
                ("dh_termino", models.DateTimeField()),
                (
                    "lider_email",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lider_email",
                        to="works.lider",
                    ),
                ),
                (
                    "planejador_email",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planejador_email",
                        to="works.planejador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TarefaColaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="works.colaborador",
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="works.tarefa"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tarefa",
            name="colaboradores",
            field=models.ManyToManyField(
                related_name="tarefas",
                through="works.TarefaColaborador",
                to="works.colaborador",
            ),
        ),
    ]
