# Generated by Django 5.1.3 on 2024-11-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0011_planejador_remove_colaborador_alterado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lider",
            name="email",
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
