# Generated by Django 5.1.3 on 2024-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0012_alter_lider_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="criado_em",
        ),
        migrations.AddField(
            model_name="lider",
            name="profissao",
            field=models.CharField(default="teste", max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lider",
            name="senha",
            field=models.CharField(max_length=12),
        ),
    ]
