# Generated by Django 5.1.5 on 2025-01-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0013_remove_tarefa_criado_em_lider_profissao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="cadastro_realizado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="foto",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
